env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  "@typescript-eslint/no-unused-vars": off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/ban-ts-comment": off