/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TvdebugImport } from './routes/tvdebug'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TvdebugRoute = TvdebugImport.update({
  id: '/tvdebug',
  path: '/tvdebug',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tvdebug': {
      id: '/tvdebug'
      path: '/tvdebug'
      fullPath: '/tvdebug'
      preLoaderRoute: typeof TvdebugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tvdebug': typeof TvdebugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tvdebug': typeof TvdebugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tvdebug': typeof TvdebugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tvdebug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tvdebug'
  id: '__root__' | '/' | '/tvdebug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TvdebugRoute: typeof TvdebugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TvdebugRoute: TvdebugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tvdebug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/tvdebug": {
      "filePath": "tvdebug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
